# Copyright (c) 2026 Varun Pratap Bhardwaj / Qualixar
# Licensed under AGPL-3.0-or-later - see LICENSE file
"""Erasure reaches the copies of a memory's words that are not projections.

The erasure owners prove a fact gone from its keyword, vector and time
projections. 4.1.21 stopped there, and an erased memory's words survived in
places no owner covered. Found on a real store and reproduced on a synthetic
one through the daemon:

* ``entity_profiles.knowledge_summary`` is the first 200 characters of every
  fact naming the entity (encoding/observation_builder.py), and
  ``fact_ids_json`` kept the erased id. The entity explorer searches that text.
* The ingestion journal kept the full original text (``raw_content``) of a
  memory whose every fact was erased: 3 of 3 fully erased memories on the real
  store, each with a COMPLETE, ``all_erased`` receipt.
* ``memory.stored`` events kept a ``content_preview`` of it.
* Summaries built from it (core memory blocks, community and consolidated
  summaries) and an entity whose only mentions were erased (its name is the
  erased words) were kept.

Everything here keeps the audit record and removes only the words: journal
rows, events and lineage stay, with ids, hashes and times. Derived summaries are
regenerated by their owners on their next pass.

Two phases, because a fact's entities can only be read while the fact exists:
``entities_of`` before the delete, ``scrub`` after it.
"""

from __future__ import annotations

import json
import logging
from contextlib import contextmanager, nullcontext
from typing import Any, Iterator

logger = logging.getLogger(__name__)

#: Attempt count at which the materializer stops claiming a journal row
#: (core/ingestion_command.py _MAX_AUTOMATIC_MATERIALIZATION_ATTEMPTS).
_PARKED_ATTEMPTS = 10
_PARKED_UNTIL = 9_999_999_999.0
ERASED_NOTE = "source text removed by erasure"


def _rows(db: Any, sql: str, params: tuple = ()) -> list[dict]:
    try:
        return [dict(r) for r in db.execute(sql, params)]
    except Exception as exc:
        if "no such table" in str(exc).lower() or "no such column" in str(exc).lower():
            return []
        raise


def _ids(raw: Any) -> list[str]:
    try:
        value = json.loads(raw) if isinstance(raw, str) else raw
    except (TypeError, ValueError):
        return [part.strip() for part in str(raw or "").split(",") if part.strip()]
    return [str(v) for v in value] if isinstance(value, list) else []


def _live(db: Any, fact_ids: list[str]) -> bool:
    for fact_id in fact_ids:
        if _rows(db, "SELECT 1 FROM atomic_facts WHERE fact_id = ? LIMIT 1", (fact_id,)):
            return True
    return False


def prepare(db: Any) -> None:
    """Before any delete: make the keyword index drop deleted words at once
    (storage/fts_residue.py). Never blocks an erasure; the repair purges later."""
    from superlocalmemory.storage.fts_residue import ensure_secure_delete

    try:
        ensure_secure_delete(db)
    except Exception as exc:
        logger.warning("keyword index secure delete not enabled: %s", exc)


def entities_of(db: Any, profile_id: str, fact_id: str) -> list[str]:
    """Entities the fact names. Call while the fact still exists."""
    found = {r["entity_id"] for r in _rows(
        db, "SELECT entity_id FROM fact_entity_associations "
        "WHERE profile_id = ? AND fact_id = ?", (profile_id, fact_id))}
    for r in _rows(db, "SELECT canonical_entities_json FROM atomic_facts "
                   "WHERE fact_id = ?", (fact_id,)):
        found.update(_ids(r.get("canonical_entities_json")))
    return sorted(found)


def _entity_still_named(db: Any, profile_id: str, entity_id: str) -> bool:
    if _rows(db, "SELECT 1 FROM fact_entity_associations WHERE entity_id = ? LIMIT 1",
             (entity_id,)):
        return True
    if _rows(db, "SELECT 1 FROM temporal_events WHERE entity_id = ? LIMIT 1", (entity_id,)):
        return True
    return bool(_rows(
        db, "SELECT 1 FROM atomic_facts WHERE profile_id = ? "
        "AND canonical_entities_json LIKE ? LIMIT 1", (profile_id, f'%"{entity_id}"%')))


def _scrub_entity_profiles(db: Any, profile_id: str, fact_id: str) -> int:
    from superlocalmemory.encoding.observation_builder import ObservationBuilder

    builder = ObservationBuilder(db)
    changed = 0
    for row in _rows(db, "SELECT profile_entry_id, entity_id, fact_ids_json FROM "
                     "entity_profiles WHERE profile_id = ? AND fact_ids_json LIKE ?",
                     (profile_id, f"%{fact_id}%")):
        remaining = [f for f in _ids(row["fact_ids_json"]) if f != fact_id]
        # The summary is rebuilt from what is left, by the same rule that wrote
        # it; the compiled view is cleared for its compiler to redo.
        summary = builder._build_summary(row["entity_id"], remaining, profile_id)
        db.execute(
            "UPDATE entity_profiles SET knowledge_summary = ?, fact_ids_json = ?, "
            "compiled_truth = '', timeline = '[]', last_compiled_at = NULL "
            "WHERE profile_entry_id = ?",
            (summary, json.dumps(remaining), row["profile_entry_id"]))
        changed += 1
    return changed


def _drop_unnamed_entities(db: Any, profile_id: str, entity_ids: list[str]) -> int:
    removed = 0
    for entity_id in entity_ids:
        if _entity_still_named(db, profile_id, entity_id):
            continue
        db.execute("DELETE FROM entity_communities WHERE entity_id = ?", (entity_id,))
        db.execute("DELETE FROM consolidated_summaries WHERE entity_id = ?", (entity_id,))
        # Aliases, profiles and events go by their ON DELETE CASCADE.
        removed += len(db.execute("DELETE FROM canonical_entities WHERE entity_id = ? "
                                  "AND profile_id = ? RETURNING entity_id",
                                  (entity_id, profile_id)))
    return removed


def _drop_derived_summaries(db: Any, profile_id: str, fact_id: str) -> int:
    removed = 0
    for table, column in (("core_memory_blocks", "source_fact_ids"),
                          ("community_summaries", "fact_ids_json"),
                          ("consolidated_summaries", "source_fact_ids")):
        try:
            gone = db.execute(f"DELETE FROM {table} WHERE profile_id = ? "  # noqa: S608
                              f"AND {column} LIKE ? RETURNING 1", (profile_id, f"%{fact_id}%"))
        except Exception as exc:
            if "no such table" in str(exc).lower():
                continue
            raise
        removed += len(gone)
    return removed


def _erased_operations(db: Any, profile_id: str, fact_id: str) -> list[dict]:
    """Journal rows naming the fact none of whose facts survives."""
    return [row for row in _rows(
        db, "SELECT operation_id, source_hash, queryable_fact_ids_json, final_fact_ids_json, "
        "raw_content "
        "FROM ingestion_operations WHERE profile_id = ? AND "
        "(queryable_fact_ids_json LIKE ? OR final_fact_ids_json LIKE ?)",
        (profile_id, f"%{fact_id}%", f"%{fact_id}%"))
        if not _live(db, _ids(row["queryable_fact_ids_json"]) + _ids(row["final_fact_ids_json"]))]


def _scrub_journal(db: Any, erased_ops: list[dict]) -> int:
    scrubbed = 0
    for row in erased_ops:
        if not row["raw_content"]:
            continue  # already scrubbed
        db.execute(
            "UPDATE ingestion_operations SET raw_content = '', raw_metadata_json = '{}', "
            "attempt_count = MAX(attempt_count, ?), next_retry_at = ?, last_error = ?, "
            "updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') "
            "WHERE operation_id = ? AND state != 'enriching'",
            (_PARKED_ATTEMPTS, _PARKED_UNTIL, ERASED_NOTE, row["operation_id"]))
        scrubbed += 1
    return scrubbed


def _event_names_live_fact(db: Any, payload: dict) -> bool:
    named = _ids(payload.get("fact_ids", []))
    if payload.get("fact_id"):
        named.append(str(payload["fact_id"]))
    return _live(db, named)


def _scrub_events(db: Any, fact_id: str, erased_ops: list[dict]) -> int:
    """Previews in events naming the fact or one of its fully erased operations.

    Not filtered by profile: the HTTP event path files every event under
    ``default`` whatever profile the memory is in, so a profile filter missed
    every non-default memory. Fact and operation ids are unique on their own.
    """
    keys = [fact_id] + [str(op["operation_id"]) for op in erased_ops] + [
        str(op["source_hash"]) for op in erased_ops if op.get("source_hash")]
    erased_op_ids = {str(op["operation_id"]) for op in erased_ops}
    scrubbed, seen = 0, set()
    for key in keys:
        for row in _rows(db, "SELECT id, payload FROM memory_events WHERE payload LIKE ? "
                         "AND payload LIKE '%content_preview%'", (f"%{key}%",)):
            if row["id"] in seen:
                continue
            seen.add(row["id"])
            try:
                payload = json.loads(row["payload"])
            except (TypeError, ValueError):
                continue
            if not isinstance(payload, dict) or "content_preview" not in payload:
                continue
            op_id = str(payload.get("operation_id") or "")
            if op_id and op_id not in erased_op_ids:
                continue  # its memory still has a live fact
            if _event_names_live_fact(db, payload):
                continue
            payload.pop("content_preview", None)
            db.execute("UPDATE memory_events SET payload = ? WHERE id = ?",
                       (json.dumps(payload), row["id"]))
            scrubbed += 1
    return scrubbed


@contextmanager
def _one_transaction(db: Any) -> Iterator[None]:
    """All of a scrub commits together, unless a caller's transaction is open."""
    state = getattr(db, "_txn_state", None)
    open_already = state is not None and (
        getattr(state, "conn", None) is not None or getattr(state, "coordinator_bound", False))
    ctx = nullcontext() if open_already or not hasattr(db, "transaction") else db.transaction()
    with ctx:
        yield


def scrub(db: Any, profile_id: str, fact_id: str,
          entity_ids: list[str] | None = None) -> dict[str, int]:
    """Remove the erased fact's words from every non-projection copy.

    Idempotent; safe to run again on a resumed or historical erasure (without
    ``entity_ids`` the entity step is skipped: they can no longer be read).
    Raises on a real storage error so the caller does not report the erasure
    complete.
    """
    with _one_transaction(db):
        erased_ops = _erased_operations(db, profile_id, fact_id)
        counts = {
            "entity_profiles_rebuilt": _scrub_entity_profiles(db, profile_id, fact_id),
            "derived_summaries_removed": _drop_derived_summaries(db, profile_id, fact_id),
            "journal_text_removed": _scrub_journal(db, erased_ops),
            "event_previews_removed": _scrub_events(db, fact_id, erased_ops),
            "unnamed_entities_removed": _drop_unnamed_entities(
                db, profile_id, list(entity_ids or ())),
        }
    if any(counts.values()):
        logger.info("erasure scrub for %s: %s", fact_id[:16], counts)
    return counts


__all__ = ["ERASED_NOTE", "entities_of", "prepare", "scrub"]
